name: Artifact Passing Workflow

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create a file
      run: echo "This is a test file" > test_file.txt

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: test-artifact
        path: test_file.txt

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: test-artifact
        path: artifacts

    - name: Show contents of artifact
      run: cat artifacts/test_file.txt
