# Fichier regroupant tous les workflows

name: base Node JS

on:
  push:
    branches: [ "main" ]
    paths:
      - 'notes/**'

jobs:
  add-update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Append update to updates.txt
      run: |
        echo "Update: $(date)" >> updates.txt

    - name: Commit changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add updates.txt
        git commit -m "Add update"
      
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ${{ secrets.NODE_VERSIONS }}
        os: [ubuntu-latest, windows-latest, macos-latest]
        parallelism: [1, 2, 3]
        
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test > test-results.xml
      env:
        CI: true
    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: test-results.xml
      
    - name: Create a file
      run: echo "This is a test file" > test_file.txt

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: test-artifact
        path: test_file.txt

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: test-artifact
        path: artifacts

    - name: Show contents of artifact
      run: cat artifacts/test_file.txt
      
  rollback:
    needs: deploy
    runs-on: ubuntu-latest
    if: failure()

    steps:
    - name: Rollback deployment
      run: |
        # Logic to perform rollback
        # Replace this with your rollback script or commands
        echo "Rolling back deployment..."

