name: updates file

on:
  push:
    paths:
      - 'notes/**'

jobs:
  add-update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Append update to updates.txt
      run: |
        echo "Update: $(date)" >> updates.txt

    - name: Commit changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add updates.txt
        git commit -m "Add update"
      
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: add-update

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to server
      run: |
        # Logic to deploy to server
        # Replace this with your deployment script or commands
        echo "Deploying to server..."


  rollback:
    needs: deploy
    runs-on: ubuntu-latest
    if: failure()

    steps:
    - name: Rollback deployment
      run: |
        # Logic to perform rollback
        # Replace this with your rollback script or commands
        echo "Rolling back deployment..."